spring:
  session:
    store-type: cookie
  datasource:
    url: jdbc:mysql://localhost:3306/alohcmute_v2
    username: root
    password: 29092003
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api/v1
  main:
    banner-mode: "off"
  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ta84578@gmail.com
    password: jesq ryxd nhvg mepd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080


#logging:
#  level:
#    root: warn
#    org.hibernate.SQL: trace
#    org.hibernate.orm.jdbc.bind: trace
#

