spring:
  session:
    store-type: cookie
  datasource:
    url: jdbc:mysql://localhost:3306/alohcmute_v2
    username: root
    password: ENC(l1V/nG3j2xo7KrX+fjj9OaseS+s2LR5lCC/vT+Hi4b69bLFTLRNvD2lWT0utAq1l)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api/v1
  main:
    banner-mode: "off"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ta84578@gmail.com
    password: ENC(ac0UEYsU7ru8imqKYhWEP2cpSTOs6BXDu5tQZVlSTeOzD3/igdXn7MgUXyklxujGJFSMuNqJ/QeFysq20J2BKw==)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

